# Permalinks
permalink:           pretty

# Setup
title:               Cameron King
tagline:             Cameron King
url:                 https://cameronking.me
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Cameron King
  url:               https://cameronking.me
  email:             cameron@uniquekings.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ckxng/ckxng.github.io.git

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist

pages_list:
  Scouting: /scouting/
  Projects: /projects/
  Consulting: /consulting/
  Resume: /resume/

