# Permalinks
permalink:           pretty

# Setup
title:               Ckxng
tagline:             Change
url:                 http://www.ckxng.com
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Cameron King
  url:               http://www.ckxng.com
  email:             cking@ckxng.com

pages_list:       
  Social Media: '/social'
  PGP: '/pgp'


# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ckxng/web.git

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
